#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : enable

#include "sssr_common.glsl"

const int GROUP_SIZE         = 8;
const int SAMPLE_BORDER      = 4;
const int SAMPLE_WINDOW_SIZE = GROUP_SIZE + 2 * SAMPLE_BORDER;

layout(set = 0, binding = 0) uniform prev_camera_data_t
{
  CameraData prevCamera;
};

layout(set = 0, binding = 1) uniform curr_camera_data_t
{
  CameraData currCamera;
};

layout(set = 0, binding = 2) uniform sampler2D texHiZ;
layout(set = 0, binding = 3) uniform sampler2D texPrevDepth;
layout(set = 0, binding = 4) uniform sampler2D texPrevGBufferNorm;
layout(set = 0, binding = 5) uniform sampler2D texCurrGBufferNorm;
layout(set = 0, binding = 6) uniform sampler2D texMetalnessRoughness;
layout(set = 0, binding = 7) uniform sampler2D texHistory;
layout(set = 0, binding = 8) uniform sampler2D texHistoryVarianceAndNumSamples;
layout(set = 0, binding = 9) uniform sampler2D texReflectionConfidence;
layout(set = 0, binding = 10) uniform sampler2D texReprojectionUV;
layout(set = 0, binding = 11) uniform sampler2D texAvgReflection;

layout(set = 0, binding = 12, rgba8) uniform writeonly image2D out_reflectionConfidence;
layout(set = 0, binding = 13, rg16f) uniform writeonly image2D out_varianceAndNumSamples;

struct SharedData
{
  vec4 reflectionConfidence;
};

shared SharedData sharedData[SAMPLE_WINDOW_SIZE * SAMPLE_WINDOW_SIZE];

/* Load samples of current texture for history neighbor clipping */
void LoadShared()
{
  ivec2 sampleWindowUpperLeftCoord = ivec2(gl_WorkGroupID.xy * GROUP_SIZE) - SAMPLE_BORDER;

  int threadIdx = int(gl_LocalInvocationIndex);
  for (int idx = threadIdx; idx < SAMPLE_WINDOW_SIZE * SAMPLE_WINDOW_SIZE; idx += GROUP_SIZE * GROUP_SIZE)
  {
    ivec2 sampleCoord = sampleWindowUpperLeftCoord + ivec2(idx % SAMPLE_WINDOW_SIZE, idx / SAMPLE_WINDOW_SIZE);
    sampleCoord = clamp(sampleCoord, ivec2(0), params.resolution - 1);
    sharedData[idx].reflectionConfidence = texelFetch(texReflectionConfidence, sampleCoord, 0);
  }

  barrier();
}

bool CheckNoDisocclusion(
  vec3 historyNormal,
  vec3 currentNormal,
  vec3 historyPosSS,
  vec3 currentPosSS
)
{
  /* -------- AMD disocclusion solution -------- */
  float normalFactor = exp(-abs(1.0f - max(0.0f, dot(currentNormal, historyNormal))) * 1.4f);

  vec3 historyPosWS = ConvertScreenToWorld(prevCamera, historyPosSS);
  vec3 currentPosWS = ConvertScreenToWorld(currCamera, currentPosSS);

  float historyDepthVS = length(historyPosWS - prevCamera.wsPos);
  float currentDepthVS = length(currentPosWS - currCamera.wsPos);

  float depthFactor = exp(-abs(historyDepthVS - currentDepthVS) / currentDepthVS);

  return normalFactor * depthFactor >= 0.9f;

  /* -------- Simple disocclusion solution -------- */
  // return (dot(historyNormal, currentNormal) > 0.999f) && (abs(historyPosSS.z - currentPosSS.z) < 0.0001f);
}

struct LocalStatistics
{
  vec3 mean;
  vec3 variance;
};

LocalStatistics EstimateLocalStatistics()
{
  LocalStatistics localStats;
  localStats.mean = vec3(0.0f);
  localStats.variance = vec3(0.0f);

  float distRadius = SAMPLE_BORDER + 1.0f;

  float totalWeight = 0.0f;
  for (int y = -SAMPLE_BORDER; y <= SAMPLE_BORDER; ++y)
  {
    float weightY = exp(-3.0f * (y * y) / (distRadius * distRadius));

    for (int x = -SAMPLE_BORDER; x <= SAMPLE_BORDER; ++x)
    {
      ivec2 localCoord = ivec2(gl_LocalInvocationID.xy) + ivec2(x, y) + SAMPLE_BORDER;
      int idx = localCoord.y * SAMPLE_WINDOW_SIZE + localCoord.x;

      vec4 reflectionConfidence = sharedData[idx].reflectionConfidence;
      if (reflectionConfidence.a > 0.0001f)
      {
        float weight = exp(-3.0f * (x * x) / (distRadius * distRadius)) * weightY;

        localStats.mean += reflectionConfidence.rgb * weight;
        localStats.variance += reflectionConfidence.rgb * reflectionConfidence.rgb * weight;
        totalWeight += weight;
      }
    }
  }

  localStats.mean /= totalWeight;
  localStats.variance /= totalWeight;

  localStats.variance = abs(localStats.variance - localStats.mean * localStats.mean);

  return localStats;
}

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE, local_size_z = 1) in;
void main()
{
  ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);
  vec2 uv = (vec2(texelCoords) + 0.5f) * params.invResolution;

  LoadShared();

  if (texelCoords.x >= params.resolution.x || texelCoords.y >= params.resolution.y)
  {
    return;
  }

  float roughness = texture(texMetalnessRoughness, uv).g;
  if (!CheckRoughnessThreshold(roughness))
  {
    imageStore(out_reflectionConfidence, texelCoords, vec4(0.0f));
    return;
  }

  ivec2 localCoord = ivec2(gl_LocalInvocationID.xy) + SAMPLE_BORDER;
  int localIdx = localCoord.y * SAMPLE_WINDOW_SIZE + localCoord.x;

  vec4 reflectionConfidence = sharedData[localIdx].reflectionConfidence;

  if (MirrorReflection(roughness))
  {
    imageStore(out_reflectionConfidence, texelCoords, reflectionConfidence);
    return;
  }

  float depth = texelFetch(texHiZ, texelCoords, params.startMip).x;
  vec3 normalWS = LoadNormal(texCurrGBufferNorm, uv);

  vec3 avgReflection = texture(texAvgReflection, uv).rgb;

  /* Load history */
  vec2 historyUV = texelFetch(texReprojectionUV, texelCoords, 0).rg;
  float historyDepth = texture(texPrevDepth, historyUV).r;
  vec3 historyNormal = LoadNormal(texPrevGBufferNorm, historyUV);

  vec4 historyReflection = vec4(0.0f);
  bool historyValid = all(lessThan(historyUV, vec2(1.0f))) &&
    all(greaterThan(historyUV, vec2(0.0f))) &&
    CheckNoDisocclusion(historyNormal, normalWS, vec3(historyUV, historyDepth), vec3(uv, depth));

  if (historyValid)
  {
    historyReflection = texture(texHistory, historyUV);

    /* Neighborhood clipping */
    LocalStatistics localStats = EstimateLocalStatistics();
    vec3 colorStd = (sqrt(localStats.variance) + length(localStats.mean - avgReflection)) * 1.4f * params.temporalStability;
    vec3 radianceMin = localStats.mean - colorStd;
    vec3 radianceMax = localStats.mean + colorStd;
    // historyReflection.rgb = HistoryClampAABB(radianceMin, radianceMax, historyReflection.rgb);
    historyReflection.rgb = HistoryClipAABB(radianceMin, radianceMax, historyReflection.rgb);
  }

  historyValid = historyValid && (historyReflection.a >= 0.99f);

  /* Temporal accumulation */
  vec3 taReflection = reflectionConfidence.rgb;
  float taConfidence = reflectionConfidence.a;

  vec2 historyVarianceAndNumSamples = texture(texHistoryVarianceAndNumSamples, historyUV).rg;
  float taNumSamples = historyValid ? historyVarianceAndNumSamples.g + 1.0f : 1.0f;
  taNumSamples = min(taNumSamples, float(params.maxAccumulationSamples));

  if (params.fallbackToAverage)
  {
    taReflection = mix(taReflection, avgReflection, 1.0f / max(taNumSamples - 1.0f, 1.0f));
  }

  float reflectionLuminance = Luminance(reflectionConfidence.rgb * reflectionConfidence.a);
  float historyLuminance = Luminance(historyReflection.rgb * historyReflection.a);
  float newVariance = abs(reflectionLuminance - historyLuminance);
  newVariance /= max(max(reflectionLuminance, historyLuminance), 0.5f);
  newVariance = newVariance * newVariance;
  float taVariance = newVariance;

  if (params.useTemporalAccumulation && params.useExponentialTemporalMean)
  {
    float taWeight = 0.9f;

    taReflection = historyValid
                    ? mix(reflectionConfidence.rgb, historyReflection.rgb, taWeight)
                    : reflectionConfidence.rgb;

    taConfidence = max(reflectionConfidence.a, historyReflection.a);

    taVariance = historyValid
                  ? mix(newVariance, historyVarianceAndNumSamples.r, taWeight)
                  : newVariance;
  }
  else if (params.useTemporalAccumulation)
  {
    taReflection = mix(historyReflection.rgb, reflectionConfidence.rgb, 1.0f / taNumSamples);
    taConfidence = max(reflectionConfidence.a, historyReflection.a);
    taVariance = mix(historyVarianceAndNumSamples.r, newVariance, 1.0f / taNumSamples);
  }

  /* Store results */
  imageStore(out_reflectionConfidence, texelCoords, vec4(taReflection, taConfidence));
  imageStore(out_varianceAndNumSamples, texelCoords, vec4(taVariance, taNumSamples, 0.0f, 0.0f));
}
