#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : enable

const int GROUP_SIZE = 8;

#include "CameraData.h"

layout(set = 0, binding = 0) uniform camera_data_t
{
  CameraData camera;
};

layout(set = 0, binding = 1) uniform sampler2D texHiZ;
layout(set = 0, binding = 2) uniform sampler2D texGBufferNorm;
layout(set = 0, binding = 3) uniform sampler2D texCurrMotionVectors;
layout(set = 0, binding = 4) uniform sampler2D texPrevColor;

layout(set = 0, binding = 5, rgba8) uniform writeonly image2D out_color;

layout(push_constant) uniform params_t
{
  ivec2 resolution;
  vec2 invResolution;

  float proj22;
  float proj23;
  float invProj00; // Precomputed coefficient, 1 / proj[0][0]
  float invProj11; // Precomputed coefficient, 1 / proj[1][1]

  int maxIterations;
  float depthThickness;

  int startMip;
  bool traceBehindSurfaces;
  bool useWorldSpaceHitConfidence;
  bool visualizeIterationCount;
} params;

vec3 ConvertWorldToScreen(vec3 posWS)
{
  vec4 csPos = camera.projView * vec4(posWS, 1.0f);
  csPos /= csPos.w;

  vec3 ssPos = csPos.xyz;
  ssPos.xy = 0.5f * ssPos.xy + 0.5f;

  return ssPos;
}

vec3 ConvertScreenToWorld(vec3 posSS)
{
  vec2  ndcXY   = 2.0f * posSS.xy - 1.0f;
  float depthVS = params.proj23 / (posSS.z - params.proj22);
  vec3  posWS   = camera.wsPos + depthVS * (camera.wsForward -
                                            camera.wsRight * ndcXY.x * params.invProj00 +
                                            camera.wsUp    * ndcXY.y * params.invProj11);

  return posWS;
}

vec3 LoadNormalWS(ivec2 texel_coords)
{
  vec3 normalWS = texelFetch(texGBufferNorm, texel_coords, 0).xyz;
  normalWS = normalize(255.0f / 127.0f * normalWS - 128.0f / 127.0f);

  return normalWS;
}

void ComputePosAndReflectionSS(
  ivec2 texel_coords,
  out vec3 out_pos_ss,
  out vec3 out_reflection_ss,
  out vec3 out_reflection_ws
)
{
  vec3 normalWS = LoadNormalWS(texel_coords);

  // Position reconstruction from depth
  // Inspired by: https://mynameismjp.wordpress.com/2010/09/05/position-from-depth-3/
  // NOTE: The uv is unjittered here, yet I'm not sure why it works to be honest... And more
  // importantly, why it doesn't work without unjittering...
  float depth   = texelFetch(texHiZ, texel_coords, 0).x;
  vec2  uv      = (vec2(texel_coords) + 0.5f) * params.invResolution - 0.5f * camera.jitterNDC;
  vec2  ndcXY   = 2.0f * uv - 1.0f;
  float depthVS = params.proj23 / (depth - params.proj22);
  vec3  posWS   = camera.wsPos + depthVS * (camera.wsForward -
                                            camera.wsRight * ndcXY.x * params.invProj00 +
                                            camera.wsUp    * ndcXY.y * params.invProj11);

  // Reflection
  vec3 incidenceWS     = posWS - camera.wsPos;
  vec3 reflectionWS    = normalize(reflect(incidenceWS, normalWS));
  vec3 reflectionEndWS = posWS + reflectionWS;

  // Transform to screen space
  out_pos_ss = ConvertWorldToScreen(posWS);

  vec3 reflectionEndSS = ConvertWorldToScreen(reflectionEndWS);
  out_reflection_ss = normalize(reflectionEndSS - out_pos_ss);

  out_reflection_ws = reflectionWS;
}

void InitialAdvanceRay(
  vec2 currentMipResolution,
  vec2 currentMipInvResolution,
  vec2 xyBoundingPlaneStep,
  vec2 uvOffset,
  vec3 reflectionSS,
  vec3 invReflectionSS,
  vec3 rayOriginSS,
  out vec3 posSS
)
{
  vec2 xyBoundingPlanes = floor(rayOriginSS.xy * currentMipResolution);
  xyBoundingPlanes += xyBoundingPlaneStep;
  xyBoundingPlanes *= currentMipInvResolution;
  xyBoundingPlanes += uvOffset;

  vec2 tIntersections = (xyBoundingPlanes - rayOriginSS.xy) * invReflectionSS.xy;
  float t = min(tIntersections.x, tIntersections.y);

  posSS = rayOriginSS + reflectionSS * t;
}

void AdvanceRay(
  inout int currentMip,
  inout vec2 currentMipResolution,
  inout vec2 currentMipInvResolution,
  vec2 xyBoundingPlaneStep,
  vec2 uvOffset,
  vec3 reflectionSS,
  vec3 invReflectionSS,
  vec3 rayOriginSS,
  inout vec3 posSS
)
{
  vec2 currentMipTexelCoords = posSS.xy * currentMipResolution;

  float zBoundingPlane = texelFetch(texHiZ, ivec2(currentMipTexelCoords), currentMip).r;
  bool aboveZBoundingPlane = posSS.z < zBoundingPlane;

  vec2 xyBoundingPlanes = floor(currentMipTexelCoords);
  xyBoundingPlanes += xyBoundingPlaneStep;
  xyBoundingPlanes *= currentMipInvResolution;
  xyBoundingPlanes += uvOffset;

  vec3 boundingPlanes = vec3(xyBoundingPlanes, zBoundingPlane);

  vec3 tIntersections = (boundingPlanes - rayOriginSS) * invReflectionSS;
  tIntersections.z = (reflectionSS.z > 0.0f) ? tIntersections.z : 3.4e+38;

  float t = min(min(tIntersections.x, tIntersections.y), tIntersections.z);

  bool lowerDetail = aboveZBoundingPlane && (floatBitsToUint(t) != floatBitsToUint(tIntersections.z));

  if (params.traceBehindSurfaces &&
      currentMip <= params.startMip &&
      !lowerDetail &&
      abs(zBoundingPlane - posSS.z) > params.depthThickness)
  {
    vec2 tIntersections = (xyBoundingPlanes - rayOriginSS.xy) * invReflectionSS.xy;
    float t = min(tIntersections.x, tIntersections.y);
    posSS = rayOriginSS + t * reflectionSS;
    return;
  }

  posSS = aboveZBoundingPlane ? (rayOriginSS + t * reflectionSS) : posSS;

  currentMip += lowerDetail ? 1 : -1;
  currentMipResolution *= lowerDetail ? 0.5f : 2.0f;
  currentMipInvResolution *= lowerDetail ? 2.0f : 0.5f;
}

float ValidateHit(vec3 posSS, vec3 reflectionWS)
{
  if (any(lessThan(posSS.xy, vec2(0.0f))) || any(greaterThan(posSS.xy, vec2(1.0f))))
  {
    return 0.0f;
  }

  ivec2 texelCoords = ivec2(posSS.xy * vec2(params.resolution));

  float depth = texelFetch(texHiZ, texelCoords, 0).r;
  if (abs(depth - 1.0f) < 0.00001f)
  {
    return 0.0f;
  }

  vec3 normalWS = LoadNormalWS(texelCoords);
  if (dot(normalWS, reflectionWS) > 0.0f)
  {
    return 0.0f;
  }

  float dist = 0.0f;

  if (params.useWorldSpaceHitConfidence) {
    vec3 hitWS = ConvertScreenToWorld(posSS);
    vec3 dWS = ConvertScreenToWorld(vec3(posSS.xy, depth));

    dist = 0.001f * length(hitWS - dWS);
  } else {
    dist = abs(posSS.z - depth);
  }

  float confidence = 1.0f - smoothstep(0.0f, params.depthThickness, dist);

  return confidence;
}

vec3 GetPreviousColor(vec3 posSS)
{
  ivec2 texelCoords = ivec2(posSS.xy * vec2(params.resolution));
  vec2 currentMotionVector = texelFetch(texCurrMotionVectors, ivec2(texelCoords), 0).xy;

  vec2 prevUV = posSS.xy + currentMotionVector;

  return texture(texPrevColor, prevUV).rgb;
}

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE, local_size_z = 1) in;
void main()
{
  ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);
  if (texelCoords.x >= params.resolution.x || texelCoords.y >= params.resolution.y)
  {
    return;
  }

  float depth = texelFetch(texHiZ, texelCoords, 0).x;
  if (abs(depth - 1.0f) < 0.00001f)
  {
    imageStore(out_color, texelCoords, vec4(0.0f, 0.0f, 0.0f, 1.0f));
    return;
  }

  vec3 rayOriginSS;
  vec3 reflectionSS;
  vec3 reflectionWS;
  ComputePosAndReflectionSS(texelCoords, rayOriginSS, reflectionSS, reflectionWS);

  vec3 invReflectionSS = 1.0f / reflectionSS;

  int currentMip = params.startMip;
  vec2 currentMipResolution = params.resolution / (currentMip == 0 ? 1.0f : exp2(float(currentMip)));
  vec2 currentMipInvResolution = 1.0f / currentMipResolution;

  vec2 xyBoundingPlaneStep = vec2(0.0f);
  xyBoundingPlaneStep.x = (reflectionSS.x >= 0.0f) ? 1.0f : 0.0f;
  xyBoundingPlaneStep.y = (reflectionSS.y >= 0.0f) ? 1.0f : 0.0f;

  vec2 uvOffset = 0.005f * currentMipInvResolution;
  uvOffset.x = (reflectionSS.x >= 0.0f) ? uvOffset.x : -uvOffset.x;
  uvOffset.y = (reflectionSS.y >= 0.0f) ? uvOffset.y : -uvOffset.y;

  vec3 currentPosSS;
  InitialAdvanceRay(
    currentMipResolution,
    currentMipInvResolution,
    xyBoundingPlaneStep,
    uvOffset,
    reflectionSS,
    invReflectionSS,
    rayOriginSS,
    currentPosSS
  );

  int i = 0;
  for (; (i < params.maxIterations) && (currentMip >= params.startMip); ++i)
  {
    AdvanceRay(
      currentMip,
      currentMipResolution,
      currentMipInvResolution,
      xyBoundingPlaneStep,
      uvOffset,
      reflectionSS,
      invReflectionSS,
      rayOriginSS,
      currentPosSS
    );
  }

  float confidence = ValidateHit(currentPosSS, reflectionWS);

  vec3 color = confidence * GetPreviousColor(currentPosSS);

  if (params.visualizeIterationCount)
  {
    color = vec3((float(i) / 300.0f), 0.0f, 0.0f);
  }

  imageStore(out_color, texelCoords, vec4(color, 1.0f));
}
