#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : enable

const int GROUP_SIZE = 8;

#include "sssr_common.glsl"

layout(set = 0, binding = 0) uniform prev_camera_data_t
{
  CameraData prevCamera;
};

layout(set = 0, binding = 1) uniform curr_camera_data_t
{
  CameraData currCamera;
};

layout(set = 0, binding = 2) uniform sampler2D texHiZ;
layout(set = 0, binding = 3) uniform sampler2D texPrevDepth;
layout(set = 0, binding = 4) uniform sampler2D texCurrGBufferNorm;
layout(set = 0, binding = 5) uniform sampler2D texCurrMotionVectors;
layout(set = 0, binding = 6) uniform sampler2D texPrevColor;
layout(set = 0, binding = 7) uniform sampler2D texMetalnessRoughness;
layout(set = 0, binding = 8) uniform samplerCube texPrefilteredEnvMap;

layout(set = 0, binding = 9, rgba8) uniform writeonly image2D out_reflectionConfidence;
layout(set = 0, binding = 10, rg16f) uniform writeonly image2D out_reprojectionUV;

uint rngState = 0;

vec3 ConvertScreenToPreviousScreen(vec3 currentPosSS)
{
  /* -------- Matrix reprojection -------- */
  // vec3 posWS = ConvertScreenToWorld(currCamera, currentPosSS);
  // return ConvertWorldToScreen(prevCamera, posWS);

  /* -------- MV reprojection -------- */
  vec2 currentUV = currentPosSS.xy;
  vec2 motionVector = texture(texCurrMotionVectors, currentUV).xy;

  vec2 prevUV = currentUV + motionVector;
  float prevDepth = texture(texPrevDepth, prevUV).r;

  return vec3(prevUV, prevDepth);
}

vec2 ReprojectReflectionRayOrigin(vec3 originSS, vec3 originWS, vec3 hitSS, vec3 hitWS)
{
  /* -------- Simple motion vector solution -------- */
  // vec2 currentUV = originSS.xy;
  // vec2 currentMotionVector = texture(texCurrMotionVectors, currentUV).xy;
  // vec2 prevUV = currentUV + currentMotionVector;
  // return prevUV;

  /* -------- EA/AMD solution -------- */
  float mirrorRayLength = length(originWS - currCamera.wsPos) + length(hitWS - originWS);
  vec3 mirrorRayDirection = normalize(originWS - currCamera.wsPos);

  vec3 mirroredHitWS = currCamera.wsPos + mirrorRayDirection * mirrorRayLength;
  vec3 prevMirroredHitSS = ConvertWorldToScreen(prevCamera, mirroredHitWS);

  return prevMirroredHitSS.xy;
}

vec3 GenReflection_ImportanceSampleGGX(float roughness, vec3 v, mat3 tbn)
{
  // Generating a reflection sample based on roughness.
  // Iterating until we the reflection vector is valid, i.e.it's not below the surface.
  // TODO: Use VNDF instead, but I don't yet understand the math behind it
  for (int i = 0; i < 2; ++i)
  {
    vec2 uniformSample = vec2(RandomFloatNormalized(rngState), RandomFloatNormalized(rngState));

    vec3 h = ImportanceSampleGGX(uniformSample, roughness, tbn);
    vec3 l = 2.0f * dot(v, h) * h - v;

    float NoL = clamp(dot(tbn[2], l), 0.0f, 1.0f);

    if (NoL > 0.0f)
    {
      return l;
    }
  }

  return vec3(0.0f);
}

void InitialAdvanceRay(
  vec2 currentMipResolution,
  vec2 currentMipInvResolution,
  vec2 xyBoundingPlaneStep,
  vec2 uvOffset,
  vec3 reflectionSS,
  vec3 invReflectionSS,
  vec3 rayOriginSS,
  out vec3 posSS
)
{
  vec2 xyBoundingPlanes = floor(rayOriginSS.xy * currentMipResolution);
  xyBoundingPlanes += xyBoundingPlaneStep;
  xyBoundingPlanes *= currentMipInvResolution;
  xyBoundingPlanes += uvOffset;

  vec2 tIntersections = (xyBoundingPlanes - rayOriginSS.xy) * invReflectionSS.xy;
  float t = min(tIntersections.x, tIntersections.y);

  posSS = rayOriginSS + reflectionSS * t;
}

void AdvanceRay(
  inout int currentMip,
  inout vec2 currentMipResolution,
  inout vec2 currentMipInvResolution,
  vec2 xyBoundingPlaneStep,
  vec2 uvOffset,
  vec3 reflectionSS,
  vec3 invReflectionSS,
  vec3 rayOriginSS,
  inout vec3 posSS
)
{
  vec2 currentMipTexelCoords = posSS.xy * currentMipResolution;

  float zBoundingPlane = texelFetch(texHiZ, ivec2(currentMipTexelCoords), currentMip).r;
  bool aboveZBoundingPlane = posSS.z < zBoundingPlane;

  vec2 xyBoundingPlanes = floor(currentMipTexelCoords);
  xyBoundingPlanes += xyBoundingPlaneStep;
  xyBoundingPlanes *= currentMipInvResolution;
  xyBoundingPlanes += uvOffset;

  vec3 boundingPlanes = vec3(xyBoundingPlanes, zBoundingPlane);

  vec3 tIntersections = (boundingPlanes - rayOriginSS) * invReflectionSS;
  tIntersections.z = (reflectionSS.z > 0.0f) ? tIntersections.z : 3.4e+38;

  float t = min(min(tIntersections.x, tIntersections.y), tIntersections.z);

  bool lowerDetail = aboveZBoundingPlane && (floatBitsToUint(t) != floatBitsToUint(tIntersections.z));

  if (params.traceBehindSurfaces &&
      currentMip <= params.startMip &&
      !lowerDetail &&
      abs(zBoundingPlane - posSS.z) > params.depthThickness)
  {
    vec2 tIntersections = (xyBoundingPlanes - rayOriginSS.xy) * invReflectionSS.xy;
    float t = min(tIntersections.x, tIntersections.y);
    posSS = rayOriginSS + t * reflectionSS;
    return;
  }

  posSS = aboveZBoundingPlane ? (rayOriginSS + t * reflectionSS) : posSS;

  currentMip += lowerDetail ? 1 : -1;
  currentMipResolution *= lowerDetail ? 0.5f : 2.0f;
  currentMipInvResolution *= lowerDetail ? 2.0f : 0.5f;
}

bool CheckNoDisocclusion(vec3 historyNormal, vec3 currentNormal, float historyDepth, float depth)
{
  return (dot(historyNormal, currentNormal) > 0.999f) && (abs(historyDepth - depth) < 0.0001f);
}

float ValidateHit(vec3 hitSS, vec3 hitWS, vec3 reflectionWS)
{
  if (any(lessThan(hitSS.xy, vec2(0.0f))) || any(greaterThan(hitSS.xy, vec2(1.0f))))
  {
    return 0.0f;
  }

  ivec2 texelCoords = ivec2(hitSS.xy * vec2(params.resolution));

  float depth = texelFetch(texHiZ, texelCoords, 0).r;
  if (abs(depth - 1.0f) < 0.00001f)
  {
    return 0.0f;
  }

  vec3 normalWS = LoadNormal(texCurrGBufferNorm, hitSS.xy);
  if (dot(normalWS, reflectionWS) > 0.0f)
  {
    return 0.0f;
  }

  float dist = 0.0f;
  vec3 dWS = ConvertScreenToWorld(currCamera, vec3(hitSS.xy, depth));

  dist = 0.005f * length(hitWS - dWS);
  return (dist < params.depthThickness) ? 1.0f : 0.0f;
}

vec3 TraceReflectionRay(
  vec3 rayOriginSS,
  vec3 reflectionSS,
  vec3 reflectionWS,
  vec3 normalWS,
  out int out_iterationCount
)
{
  vec3 invReflectionSS = 1.0f / reflectionSS;

  int currentMip = params.startMip;
  vec2 currentMipResolution = params.resolution / (currentMip == 0 ? 1.0f : exp2(float(currentMip)));
  vec2 currentMipInvResolution = 1.0f / currentMipResolution;

  vec2 xyBoundingPlaneStep = vec2(0.0f);
  xyBoundingPlaneStep.x = (reflectionSS.x >= 0.0f) ? 1.0f : 0.0f;
  xyBoundingPlaneStep.y = (reflectionSS.y >= 0.0f) ? 1.0f : 0.0f;

  vec2 uvOffset = 0.005f * currentMipInvResolution;
  uvOffset.x = (reflectionSS.x >= 0.0f) ? uvOffset.x : -uvOffset.x;
  uvOffset.y = (reflectionSS.y >= 0.0f) ? uvOffset.y : -uvOffset.y;

  vec3 currentPosSS;
  InitialAdvanceRay(
    currentMipResolution,
    currentMipInvResolution,
    xyBoundingPlaneStep,
    uvOffset,
    reflectionSS,
    invReflectionSS,
    rayOriginSS,
    currentPosSS
  );

  int i = 0;
  for (; (i < params.maxIterations) && (currentMip >= params.startMip); ++i)
  {
    AdvanceRay(
      currentMip,
      currentMipResolution,
      currentMipInvResolution,
      xyBoundingPlaneStep,
      uvOffset,
      reflectionSS,
      invReflectionSS,
      rayOriginSS,
      currentPosSS
    );
  }

  out_iterationCount = i;

  return currentPosSS;
}

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE, local_size_z = 1) in;
void main()
{
  ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);
  if (texelCoords.x >= params.resolution.x || texelCoords.y >= params.resolution.y)
  {
    return;
  }

  float depth = texelFetch(texHiZ, texelCoords, 0).x;
  if (abs(depth - 1.0f) < 0.00001f)
  {
    imageStore(out_reflectionConfidence, texelCoords, vec4(0.0f));
    return;
  }

  float roughness = texelFetch(texMetalnessRoughness, texelCoords, 0).g;
  if (!CheckRoughnessThreshold(roughness))
  {
    imageStore(out_reflectionConfidence, texelCoords, vec4(0.0f));
    return;
  }

  vec2 uv = (vec2(texelCoords) + 0.5f) * params.invResolution;
  vec3 normalWS = LoadNormal(texCurrGBufferNorm, texelCoords);

  vec3 posSS = vec3(uv, depth);

  // NOTE: The uv is unjittered here, yet I'm not sure why it works to be honest... And more
  // importantly, why it doesn't work without unjittering...
  vec3 posWS = ConvertScreenToWorld(currCamera, vec3(uv - 0.5f * currCamera.jitterNDC, depth));

  vec3 incidenceWS  = normalize(posWS - currCamera.wsPos);

  vec4 resultColor = vec4(0.0f);
  vec2 reprojectionUV = vec2(0.0f);
  int iterationCount = 0;

  if (MirrorReflection(roughness))
  {
    vec3 reflectionWS = normalize(reflect(incidenceWS, normalWS));
    vec3 reflectionSS = ConvertDirectionWorldToScreen(currCamera, posWS, posSS, reflectionWS);

    // Trace the reflection sample
    vec3 hitSS = TraceReflectionRay(posSS, reflectionSS, reflectionWS, normalWS, iterationCount);
    vec3 hitWS = ConvertScreenToWorld(currCamera, hitSS);

    // Sample the scene color from the previous frame and validate the hit point
    vec3 reflectionColor = texture(texPrevColor, ConvertScreenToPreviousScreen(hitSS).xy).rgb;
    float confidence = ValidateHit(hitSS, hitWS, reflectionWS);

    resultColor = vec4(reflectionColor, confidence);
  }
  else
  {
    // Initialize the rng
    // rngState = (texelCoords.x * 1973U + texelCoords.y * 9277U + (resultSize + 1) * 26699U) | 1U;
    rngState = ((texelCoords.x * 1973U + texelCoords.y * 9277U) ^
                ((params.frameIdx % 194371U) * 3U)) | 1U;

    mat3 tbn = ConstructTBN(normalWS);

    // Importance sample the reflection vector
    vec3 reflectionWS = GenReflection_ImportanceSampleGGX(roughness, -incidenceWS, tbn);
    vec3 reflectionSS = ConvertDirectionWorldToScreen(currCamera, posWS, posSS, reflectionWS);

    // Trace the reflection sample
    vec3 hitSS = TraceReflectionRay(posSS, reflectionSS, reflectionWS, normalWS, iterationCount);
    vec3 hitWS = ConvertScreenToWorld(currCamera, hitSS);

    // Sample the scene color from the previous frame and validate the hit point
    vec3 reflectionColor = texture(texPrevColor, ConvertScreenToPreviousScreen(hitSS).xy).rgb;
    float confidence = ValidateHit(hitSS, hitWS, reflectionWS);

    // Sample environment map as a fallback
    float smoothness = clamp(1.0f - roughness, 0.0f, 1.0f);
    float lerpFactor = smoothness * (sqrt(smoothness) + roughness);
    vec3 R = mix(normalWS, reflect(incidenceWS, normalWS), lerpFactor);

    float envMip = roughness * float(params.envMapMips - 1);
    vec3 environmentFallback = textureLod(texPrefilteredEnvMap, R, envMip).rgb;

    // Mix the reflection color with the fallback based on confidence
    reflectionColor = mix(environmentFallback, reflectionColor, confidence);

    resultColor.rgb = reflectionColor;
    resultColor.a = 1.0f;

    // Get reprojection UV
    reprojectionUV = ReprojectReflectionRayOrigin(posSS, posWS, hitSS, hitWS);
  }

  if (params.visualizeIterationCount)
  {
    resultColor = vec4((float(iterationCount) / 300.0f), 0.0f, 0.0f, 0.0f);
  }

  imageStore(out_reflectionConfidence, texelCoords, resultColor);
  imageStore(out_reprojectionUV, texelCoords, vec4(reprojectionUV, 0.0f, 0.0f));
}
