#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : enable

#include "sssr_common.glsl"

const int GROUP_SIZE         = 8;
const int SAMPLE_BORDER      = 3;
const int SAMPLE_WINDOW_SIZE = GROUP_SIZE + 2 * SAMPLE_BORDER;

layout(set = 0, binding = 0) uniform curr_camera_data_t
{
  CameraData currCamera;
};

layout(set = 0, binding = 1) uniform sampler2D texHiZ;
layout(set = 0, binding = 2) uniform sampler2D texCurrGBufferNorm;
layout(set = 0, binding = 3) uniform sampler2D texMetalnessRoughness;
layout(set = 0, binding = 4) uniform sampler2D texReflectionConfidence;

layout(set = 0, binding = 5, rgba8) uniform writeonly image2D out_reflectionConfidence;

struct NeighborData
{
  vec4 reflectionConfidence;
  vec3 normalWS;
  vec3 positionWS;
  float depth;
};

shared NeighborData sharedData[SAMPLE_WINDOW_SIZE * SAMPLE_WINDOW_SIZE];

void LoadShared()
{
  ivec2 sampleWindowUpperLeftCoord = ivec2(gl_WorkGroupID.xy * GROUP_SIZE) - SAMPLE_BORDER;

  int threadIdx = int(gl_LocalInvocationIndex);
  for (int idx = threadIdx; idx < SAMPLE_WINDOW_SIZE * SAMPLE_WINDOW_SIZE; idx += GROUP_SIZE * GROUP_SIZE)
  {
    ivec2 sampleCoord = sampleWindowUpperLeftCoord + ivec2(idx % SAMPLE_WINDOW_SIZE, idx / SAMPLE_WINDOW_SIZE);
    sampleCoord = clamp(sampleCoord, ivec2(0), params.resolution - 1);
    vec2 uv = (vec2(sampleCoord) + 0.5f) * params.invResolution;

    NeighborData neighborData;
    neighborData.reflectionConfidence = texelFetch(texReflectionConfidence, sampleCoord, 0);
    neighborData.normalWS = LoadNormal(texCurrGBufferNorm, uv);
    neighborData.depth = texelFetch(texHiZ, sampleCoord, params.startMip).r;
    neighborData.positionWS = ConvertScreenToWorld(currCamera, vec3(uv, neighborData.depth));

    sharedData[idx] = neighborData;
  }

  barrier();
}

float NormalWeight(vec3 normalWS, vec3 sampleNormalWS)
{
  int sigma = 128;
  return pow(max(0.0f, dot(normalWS, sampleNormalWS)), sigma);
}

float PlaneDistance(vec3 positionWS, vec3 samplePositionWS, vec3 planeNormalWS)
{
  return abs(dot(positionWS - samplePositionWS, planeNormalWS));
}

float DepthWeight(vec3 positionWS, vec3 samplePositionWS, vec3 normalWS)
{
  return PlaneDistance(positionWS, samplePositionWS, normalWS) < 0.01 ? 1.0 : 0.0;
}

float GaussianWeight(float x)
{
  float sigma = 3.0f;
  return exp(-(x * x) / (2.0 * sigma * sigma));
}

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE, local_size_z = 1) in;
void main()
{
  ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);
  vec2 uv = (vec2(texelCoords) + 0.5f) * params.invResolution;

  LoadShared();

  if (texelCoords.x >= params.resolution.x || texelCoords.y >= params.resolution.y)
  {
    return;
  }

  float roughness = texture(texMetalnessRoughness, uv).g;
  if (!CheckRoughnessThreshold(roughness))
  {
    imageStore(out_reflectionConfidence, texelCoords, vec4(0.0f));
    return;
  }

  ivec2 centerCoord = ivec2(gl_LocalInvocationID.xy) + SAMPLE_BORDER;
  int centerIdx = centerCoord.y * SAMPLE_WINDOW_SIZE + centerCoord.x;

  NeighborData centerData = sharedData[centerIdx];

  if (!params.useFilter)
  {
    imageStore(out_reflectionConfidence, texelCoords, centerData.reflectionConfidence);
    return;
  }

  vec4 result = vec4(0.0f);
  float totalWeight = 0.0f;

  for (int y = -SAMPLE_BORDER; y <= SAMPLE_BORDER; ++y)
  {
    float gaussianWeightY = GaussianWeight(float(y));

    for (int x = -SAMPLE_BORDER; x <= SAMPLE_BORDER; ++x)
    {
      int sampleIdx = centerIdx + y * SAMPLE_WINDOW_SIZE + x;

      NeighborData sampleData = sharedData[sampleIdx];

      float weight = NormalWeight(centerData.normalWS, sampleData.normalWS) *
        DepthWeight(centerData.positionWS, sampleData.positionWS, centerData.normalWS) *
        GaussianWeight(x) * gaussianWeightY;

      result += sampleData.reflectionConfidence * weight;
      totalWeight += weight;
    }
  }

  if (totalWeight > 0.0f)
  {
    result /= totalWeight;
  }

  imageStore(out_reflectionConfidence, texelCoords, result);
}
